### ISSUE TITLE
Where To Get CMake 3.23?

### ISSUE THREAD

**Issue by nlogozzo** [fredemmott/cmake-cpp-winrt-winui3#1]
I set `cmake_minimum_required(VERSION 3.23)`, however, I am getting the error `CMake 3.23 or higher is required.  You are running version 3.22.22040401-MSVC_2`
How can I update the version to 3.23, as 3.22 is the version bundled with visual studio.

**Comment by fredemmott** [comment]
See https://cmake.org/install/ - if you use Scoop, that also works
