### ISSUE TITLE
error MIDL2011: [msg]unresolved type declaration [context]: Microsoft.UI.Xaml.Controls.Page

### ISSUE THREAD

**Issue by stoperro** [fredemmott/cmake-cpp-winrt-winui3#3]
Hi,
I'm getting:
```
...\DemoPage.idl(5): error MIDL2011: [msg]unresolved type declaration [context]: Microsoft.UI.Xaml.Controls.Page [ RuntimeClass 'DemoApp.DemoPage'  ]
```

I'm using CMake 3.24.0-rc3 and I think Windows App SDK 1.1. 

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.2.6

**Comment by fredemmott** [comment]
How're you building it? If you're building within visual studio, set the CMake Generator to Visual Studio - see https://docs.microsoft.com/en-us/cpp/build/customize-cmake-settings?view=msvc-170#cmake-generator

It defaults to ninja, which is unable to deal with C++/WinRT and the xaml stuff

**Comment by stoperro** [comment]
I've used GUI CMake tool to generate the project/solution files. Tried also generate from command line (specifying MSVC generator to get .sln files), but it had same effect - files generated correctly, but error when trying to build.

**Comment by fredemmott** [comment]
Does this work for you?

```
git clean -ffdx
mkdir build
cd build
cmake ..
cmake --build . --config Debug
```

**Comment by stoperro** [comment]
Yes! :)

Hmm, maybe the `cmake --build` makes the difference. If I do:
```
git clean -ffdx
mkdir build
cd build
cmake ..
```
...and open solution in IDE and try to build from it it fails (this is what I was doing, or from CMake GUI). But then if I run the last command you provided:
`cmake --build . --config Debug`, it makes the solution work, and now I can build from withing IDE.

**Comment by fredemmott** [comment]
I mostly use Visual Studio *Code* where it does work; this sounds like it might be a bug in full Visual Studio's CMake support :/

**Comment by fredemmott** [comment]
Oh, one idea: this depends on *very* recent cmake features, which are more recent than Visual Studio's cmake. If Visual Studio automatically 'updates' it with it's included version of CMake instead of your 3.24-rc3 installation, that could lead to problems

**Comment by stoperro** [comment]
Your CMake requires 3.23 (`cmake_minimum_required(VERSION 3.23)`), in fact, when I tried instead to "Open Folder" with CMake project, it indeed failed as it uses 3.22. But this doesn't happen for GUI or command line generated project/solution files.

**Comment by fredemmott** [comment]
Interesting; the generated vcxproj files do end up calling cmake again themselves, but at least for me they have the full path to the specific cmake they're using.

I'm going to close this as it seems like an issue in Visual Studio that is likely be to fixed when they next update cmake.
