### ISSUE TITLE
I had try to use your project like example for UWP app with cmake but it didn't compile

### ISSUE THREAD

**Issue by kosbar** [fredemmott/cmake-cpp-winrt-winui3#4]
Error | MIDL2011 | [msg]unresolved type declaration [context]: Microsoft.UI.Xaml.Controls.Page [ RuntimeClass 'DemoApp.DemoPage'  ] | DemoApp | C:\Users\RDP_Konstantin\projects\cmake-cpp-winrt-winui3\src\DemoPage.idl 

cmake version 3.23.1 Windows 10, VS 17 Visual Studio 17 2022

**Comment by fredemmott** [comment]
Most likely, visual studio is not configured to use the msbuild generator - it defaults to ninja.

The project still builds reliably with vscode or running cmake + `cmake --build` from a terminal. For a real-world example: https://github.com/OpenKneeboard/OpenKneeboard/blob/d94e02f249cf22d6cdabefd3382eb58def8e088a/.github/workflows/ci.yml#L43-L54
