### ISSUE TITLE
Can we not use self-contained mode? 

### ISSUE THREAD

**Issue by harshith187** [fredemmott/cmake-cpp-winrt-winui3#5]
Hi, 

Thank you for this sample, this was very helpful. Can we do this without using self-contained mode? because it carries the Windows App SDK dependencies with it so it fills up my debug directory with Windows App SDK dependencies.

**Comment by fredemmott** [comment]
Yep, changing the relevant properties in the cmake and .props file works; this project targets self contained because of how frequently non-self-contained has broken (e.g completely unable to start if unpackaged, or different builds of the windows app sdk msix packages with conflicting ids)

**Comment by fredemmott** [comment]
You’ll also need to add the PackageDependency to the appxmanifest
